package com.openbravo.pos.inventory;

import javax.swing.JComponent;
import javax.swing.JOptionPane;
import com.openbravo.basic.BasicException;
import com.openbravo.data.gui.MessageInf;
import com.openbravo.pos.customers.CustomerInfoExt;
import com.openbravo.pos.customers.DataLogicCustomers;

import com.openbravo.pos.forms.AppLocal;
import com.openbravo.pos.forms.AppView;
import com.openbravo.pos.forms.BeanFactoryApp;
import com.openbravo.pos.forms.BeanFactoryException;

import com.openbravo.pos.forms.JPanelView;

/**15-09-2014 JOSE DE PAZ JDP REQ140914 Versión inicial
 *                                      Clase para actualizar el CUPO de los clientes
* 
*/



public class ActualizarCuposPanel extends javax.swing.JPanel implements JPanelView, BeanFactoryApp{
	    
	private static final long serialVersionUID = 1L;
		private AppView app;
	    private DataLogicCustomers dlcustomers;
	    private CustomerInfoExt customerext;
	 

	    
	    public ActualizarCuposPanel() {

	        initComponents();      
	        txtTaxId.addEditorKeys(m_jKeys);	    
	    }

	    public void init(AppView app) throws BeanFactoryException {
	        this.app = app;
	        dlcustomers = (DataLogicCustomers) app.getBean("com.openbravo.pos.customers.DataLogicCustomersCreate");
	    }

	    public Object getBean() {
	        return this;
	    }

	    public String getTitle() {
	        return AppLocal.getIntString("Menu.StockActualizarCuposMasivo");
	    }

	    public void activate() throws BasicException {
	    	txtTaxId.reset();	     
	    }

	    public boolean deactivate() {	       
	            return true;
	    }

	    public JComponent getComponent() {
	        return this;
	    }
	       

	    private void save() {

	    	try {
	    		customerext=new CustomerInfoExt("", "", "");
	    		customerext.setMaxdebt(txtTaxId.getValue());
	            dlcustomers.updateCustomerMaxDebt(customerext);
	            JOptionPane.showMessageDialog(this,"El CUPO fue actualizado con éxito.", "Cupo Cliente", JOptionPane.PLAIN_MESSAGE);
	            txtTaxId.reset();	    
	           
	        } catch (BasicException e) {
	            MessageInf msg = new MessageInf(MessageInf.SGN_NOTICE, AppLocal.getIntString("message.nosavemaxdebt"), e);
	            msg.show(this);
	        }
	       
	    }

	   

	    /** This method is called from within the constructor to
	     * initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is
	     * always regenerated by the Form Editor.
	     */
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	    private void initComponents() {
	      

	        jPanel2 = new javax.swing.JPanel();
	        jPanel3 = new javax.swing.JPanel();
	        jPanel4 = new javax.swing.JPanel();
	        btnSave = new javax.swing.JButton();
	        jSeparator1 = new javax.swing.JSeparator();
	      
	     
	        jPanel5 = new javax.swing.JPanel();
	        m_jKeys = new com.openbravo.editor.JEditorKeys();
	      
	     
	      
	        txtTaxId = new com.openbravo.editor.JEditorCurrency();
	        jLabel7 = new javax.swing.JLabel();

	        setLayout(new java.awt.BorderLayout());

	        
	        jPanel2.setLayout(null);

	       
	        txtTaxId.setFocusable(false);
	        txtTaxId.setRequestFocusEnabled(false);
	        jPanel2.add(txtTaxId);
	        txtTaxId.setBounds(160, 20, 240, 20);

	        jLabel7.setText(AppLocal.getIntString("Label.Cupo")); // NOI18N
	        jPanel2.add(jLabel7);
	        jLabel7.setBounds(20, 20, 140, 15);
	     

	        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/filesave.png"))); // NOI18N
	        btnSave.setFocusPainted(false);
	        btnSave.setFocusable(false);	       
	        btnSave.setRequestFocusEnabled(false);
	        btnSave.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                btnSaveActionPerformed(evt);
	            }
	        });
	        jPanel2.add(btnSave);
	        btnSave.setBounds(20, 60, 100, 40);
	        jPanel2.add(jSeparator1);       

	      
	        add(jPanel2, java.awt.BorderLayout.CENTER);

	    

	        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

	        m_jKeys.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                m_jKeysActionPerformed(evt);
	            }
	        });
	        jPanel4.add(m_jKeys);

	        jPanel4.add(jPanel5);

	        jPanel3.add(jPanel4, java.awt.BorderLayout.NORTH);

	        add(jPanel3, java.awt.BorderLayout.EAST);
	    }// </editor-fold>//GEN-END:initComponents
	  
	    private void m_jKeysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_jKeysActionPerformed

	      
	        
	    }//GEN-LAST:event_m_jKeysActionPerformed

	    
	    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
	    	
	             save();
	       
	    }//GEN-LAST:event_btnSaveActionPerformed
	    
	    
	    // Variables declaration - do not modify//GEN-BEGIN:variables

	    private javax.swing.JButton btnSave;
	    private javax.swing.JLabel jLabel7;
	    private javax.swing.JPanel jPanel2;
	    private javax.swing.JPanel jPanel3;
	    private javax.swing.JPanel jPanel4;
	    private javax.swing.JPanel jPanel5;
	    private javax.swing.JSeparator jSeparator1;
	    private com.openbravo.editor.JEditorKeys m_jKeys;
	    private com.openbravo.editor.JEditorCurrency txtTaxId;
	    // End of variables declaration//GEN-END:variables
	}
