package com.openbravo.pos.reports;

import java.awt.Component;
import java.awt.event.ActionListener;
import java.util.List;

import com.openbravo.basic.BasicException;
import com.openbravo.data.gui.ComboBoxValModel;
import com.openbravo.data.loader.Datas;
import com.openbravo.data.loader.QBFCompareEnum;
import com.openbravo.data.loader.SentenceList;
import com.openbravo.data.loader.SerializerWrite;
import com.openbravo.data.loader.SerializerWriteBasic;
import com.openbravo.pos.forms.AppView;
import com.openbravo.pos.forms.DataLogicSales;

public class JParamsTipoPagoRecarga extends javax.swing.JPanel implements
		ReportEditorCreator {

	private SentenceList m_sentlocations;
	private ComboBoxValModel m_LocationsModel;

	/** Creates new form JParamsLocation */
	public JParamsTipoPagoRecarga() {
		initComponents();
	}

	public void init(AppView app) {

		DataLogicSales dlSales = (DataLogicSales) app
				.getBean("com.openbravo.pos.forms.DataLogicSalesCreate");

		// El modelo de locales
		m_sentlocations = dlSales.getTipoPagoRecargaList();
		m_LocationsModel = new ComboBoxValModel();
	}

	public void activate() throws BasicException {
		List a = m_sentlocations.list();
		addFirst(a);
		m_LocationsModel = new ComboBoxValModel(a);
		m_LocationsModel.setSelectedFirst();
		m_jLocation.setModel(m_LocationsModel); // refresh model
	}

	public SerializerWrite getSerializerWrite() {
		return new SerializerWriteBasic(new Datas[] { Datas.OBJECT,
				Datas.STRING });
	}

	public Component getComponent() {
		return this;
	}

	protected void addFirst(List a) {
		// do nothing
	}

	public void addActionListener(ActionListener l) {
		m_jLocation.addActionListener(l);
	}

	public void removeActionListener(ActionListener l) {
		m_jLocation.removeActionListener(l);
	}

	public Object createValue() throws BasicException {

		return new Object[] {
				m_LocationsModel.getSelectedKey() == null ? QBFCompareEnum.COMP_NONE
						: QBFCompareEnum.COMP_EQUALS,
				m_LocationsModel.getSelectedKey() };
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		m_jLocation = new javax.swing.JComboBox();
		jLabel8 = new javax.swing.JLabel();

		setBorder(javax.swing.BorderFactory.createTitledBorder("Pago Recarga")); // NOI18N
		setPreferredSize(new java.awt.Dimension(400, 60));
		setLayout(null);
		add(m_jLocation);
		m_jLocation.setBounds(161, 20, 220, 20);

		jLabel8.setText("Tipo"); // NOI18N
		add(jLabel8);
		jLabel8.setBounds(20, 20, 110, 14);
	}// </editor-fold>//GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel jLabel8;
	private javax.swing.JComboBox m_jLocation;
	// End of variables declaration//GEN-END:variables

}
