package com.openbravo.pos.reports;

import com.openbravo.basic.BasicException;
import com.openbravo.data.gui.ComboBoxValModel;
import com.openbravo.data.gui.ListKeyed;
import com.openbravo.data.loader.Datas;
import com.openbravo.data.loader.QBFCompareEnum;
import com.openbravo.data.loader.SentenceList;
import com.openbravo.data.loader.SerializerWrite;
import com.openbravo.data.loader.SerializerWriteBasic;
import com.openbravo.pos.forms.AppLocal;
import com.openbravo.pos.forms.DataLogicSales;
import com.openbravo.pos.forms.AppView;
import com.openbravo.pos.inventory.SubCentroCostoInfo;

import java.awt.Component;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;

public class JParamsCentroCosto extends javax.swing.JPanel implements
		ReportEditorCreator {

    private SentenceList m_sentcentrocosto;
    private SentenceList m_sentsubcentrocosto;
    private ComboBoxValModel  m_CentroCostoModel, m_SubCentroCostoModel;
    private ListKeyed subcentrocostocollection;
    private DataLogicSales dlSalesAux; 

	/** Creates new form JParamsLocation */
	public JParamsCentroCosto() {
		initComponents();
	}

	public void init(AppView app) {

		DataLogicSales dlSales = (DataLogicSales) app
				.getBean("com.openbravo.pos.forms.DataLogicSalesCreate");
		dlSalesAux=dlSales;

		// El modelo de locales
		m_sentcentrocosto = dlSales.getCentroCostoList();
		m_CentroCostoModel = new ComboBoxValModel();
		
	    m_sentsubcentrocosto=dlSales.getSubCentroCostoList();
	    m_SubCentroCostoModel = new ComboBoxValModel();
	    cboSubCentroCosto.setModel(m_SubCentroCostoModel);  
        
	}

	public void activate() throws BasicException {
		
		
		
		List a = m_sentcentrocosto.list();
		a.add(0,null);
		addFirst(a);
		m_CentroCostoModel = new ComboBoxValModel(a);
		m_CentroCostoModel.setSelectedFirst();
		cboCentroCosto.setModel(m_CentroCostoModel); // refresh model
		
		
	/*	List b = m_sentsubcentrocosto.list();
		b.add(0,null);
		m_SubCentroCostoModel = new ComboBoxValModel(b);
		m_SubCentroCostoModel.setSelectedFirst();
	    cboSubCentroCosto.setModel(m_SubCentroCostoModel); */
	   
	   
	}

	public SerializerWrite getSerializerWrite() {
		return new SerializerWriteBasic(new Datas[] { Datas.OBJECT,
				Datas.STRING,Datas.OBJECT,
				Datas.STRING });
	}

	public Component getComponent() {
		return this;
	}

	protected void addFirst(List a) {
		// do nothing
	}

	public void addActionListener(ActionListener l) {
		cboCentroCosto.addActionListener(l);
	}

	public void removeActionListener(ActionListener l) {
		cboCentroCosto.removeActionListener(l);
	}

	public Object createValue() throws BasicException {

	//	String aded=this.m_CentroCostoModel.getSelectedKey().toString();
 	//    System.out.println("Hola:"+ aded+":");
		//if (this.m_CentroCostoModel.getSelectedKey())
		return new Object[] {
				m_CentroCostoModel.getSelectedKey() == null ? QBFCompareEnum.COMP_NONE
						: QBFCompareEnum.COMP_EQUALS,
						m_CentroCostoModel.getSelectedKey(),
						m_SubCentroCostoModel.getSelectedKey() == null ? QBFCompareEnum.COMP_NONE
								: QBFCompareEnum.COMP_EQUALS,
								m_SubCentroCostoModel.getSelectedKey()};
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		cboCentroCosto = new javax.swing.JComboBox();
		lblCentroCosto = new javax.swing.JLabel();
		cboSubCentroCosto = new javax.swing.JComboBox();
		lblSubCentroCosto = new javax.swing.JLabel();

		setBorder(javax.swing.BorderFactory.createTitledBorder(AppLocal
				.getIntString("Label.PorCentroCosto"))); // NOI18N
		setPreferredSize(new java.awt.Dimension(400, 80));
		setLayout(null);
		

		lblCentroCosto.setText(AppLocal.getIntString("Label.CentroCosto")); // NOI18N
		add(lblCentroCosto);
		lblCentroCosto.setBounds(20, 20, 110, 14);
		
		
		cboCentroCosto.addItemListener(new java.awt.event.ItemListener() {
	        	@Override
	            public void itemStateChanged(java.awt.event.ItemEvent evt) {
	               if (evt.getStateChange()==java.awt.event.ItemEvent.SELECTED)
	               {
					try {
						
						 if(evt.getItem().toString().length()>0)
						   CentroCostoActionPerformed(evt);
						 else {
							 List bb = new ArrayList();
						     bb.add(0,null);
						     m_SubCentroCostoModel = new ComboBoxValModel(bb);
						     cboSubCentroCosto.setModel(m_SubCentroCostoModel);  
						 }
					} catch (BasicException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
	               }	
	               else
	               {
	            	   if(cboCentroCosto.getSelectedIndex()==-1)
	            	   {
	            		   List bb = new ArrayList();
						     bb.add(0,null);
						     m_SubCentroCostoModel = new ComboBoxValModel(bb);
						     cboSubCentroCosto.setModel(m_SubCentroCostoModel); 
	            	   }
	            	   
	               }
	            }
	        });
		add(cboCentroCosto);
		cboCentroCosto.setBounds(161, 20, 220, 20);
		
		lblSubCentroCosto.setText(AppLocal.getIntString("Label.SubCentroCosto")); // NOI18N
		add(lblSubCentroCosto);
		lblSubCentroCosto.setBounds(20, 50, 130, 14);
		
		add(cboSubCentroCosto);
		cboSubCentroCosto.setBounds(161, 50, 220, 20);
	}// </editor-fold>//GEN-END:initComponents
	
	
	 private void CentroCostoActionPerformed(java.awt.event.ItemEvent evt) throws BasicException {//GEN-FIRST:event_jButton3ActionPerformed	

	    	
	    	java.util.List<SubCentroCostoInfo> subCentrosCosto = dlSalesAux.getSubCentroCostoList1(m_CentroCostoModel.getSelectedKey().toString());
	    	subcentrocostocollection = new ListKeyed<SubCentroCostoInfo>(subCentrosCosto);
	    	m_SubCentroCostoModel=new ComboBoxValModel(subCentrosCosto);
	    	cboSubCentroCosto.setModel(m_SubCentroCostoModel);
	    }

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel lblCentroCosto;
	private javax.swing.JComboBox cboCentroCosto;
	private javax.swing.JLabel lblSubCentroCosto;
	private javax.swing.JComboBox cboSubCentroCosto;
	// End of variables declaration//GEN-END:variables
}